---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: config/_ytt_lib
  contents:
  - path: github.com/GoogleCloudPlatform/metacontroller
    git:
      url: https://github.com/GoogleCloudPlatform/metacontroller
      ref: v0.4.0
    includePaths:
    - manifests/*
  - path: github.com/cloudfoundry/cf-k8s-networking
    git:
      url: https://github.com/cloudfoundry/cf-k8s-networking
      ref: b4375d0b13cb853ee402a9530b54188772c24ff6
    includePaths:
    - cfroutesync/crds/**/*
    - config/cfroutesync/**/*
  - path: github.com/cloudfoundry/capi-k8s-release
    git:
      url: https://github.com/cloudfoundry/capi-k8s-release
      ref: 26aa96fed336505b048030c120266aa4a4871092
    includePaths:
    - templates/**/*
    - values.yml
  - path: github.com/cloudfoundry/uaa
    git:
      url: https://github.com/cloudfoundry/uaa
      ref: 5f3af8a7b158c77320c04b45efae99c936ad0a7d
    includePaths:
    - k8s/templates/**/*
    - k8s/values/default-values.yml
  - path: istio
    manual: {}
  - path: eirini
    manual: {}
  - path: postgres
    manual: {}
  - path: docker-registry
    manual: {}
- path: build/docker-registry/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      # chart version: 1.9.1
      # app version: 2.7.1
      ref: 2b1e12f5f748a69a1429a1bb015bc34f3124c4e2
    includePaths:
    - stable/docker-registry/**/*
